### ISSUE TITLE
扫描后没有结果显示

### ISSUE THREAD

**Issue by joexiayong** [elliot-bia/nessus#10]
多次扫描，每次均无结果显示。
![image](https://user-images.githubusercontent.com/22511048/186852770-4267126f-afe3-4293-a450-67e0090a0e77.png)
![image](https://user-images.githubusercontent.com/22511048/186852775-81a415b3-5398-4f8e-b0e1-2667927e9239.png)

**Comment by elliot-bia** [comment]
Hosts数量为0，请检查目标是否可达
