### ISSUE TITLE
podman报错

### ISSUE THREAD

**Issue by qxqzx3489** [elliot-bia/nessus#17]
192.168.1.115/10180 The network interface 'tap0' does not support packet forgery. This prevents Nessus from determining whether some of the target hosts are alive and from performing a full port scan against them. You may partially work around this problem by editing your scan settings to disable 'Ping' (Uncheck General->Ping host) and by providing Nessus with credentials to the remote host to prevent a port scan from taking place, however it would be preferable to scan over a different network interface.

**Comment by qxqzx3489** [comment]
网上搜到解决办法是
setcap "cap_net_admin,cap_net_raw,cap_sys_resource+eip" /opt/nessus/sbin/nessusd 
setcap "cap_net_admin,cap_net_raw,cap_sys_resource+eip" /opt/nessus/sbin/nessus-servic
镜像里面没这个命令,我要怎么解决呢

**Comment by elliot-bia** [comment]
未接触过，感觉是因为启用了ping主机探测，关掉试试
