### ISSUE TITLE
可以更新一下插件吗

### ISSUE THREAD

**Issue by killdayu** [elliot-bia/nessus#2]
我自己手动更新了一下许可证有问题，扫描的时候不显示插件

**Comment by elliot-bia** [comment]
🤣好的，我今天晚点更一版新的插件出来
OK, I will update the plugins later.

自动更新版其实已经做好了，最近比较忙没放出来，可以关注[推特](https://twitter.com/Elliot58616851)
The auto update plugins verion has been finish, but I got a little busy these day, you can follow my [twitter](https://twitter.com/Elliot58616851) for latest news

**Comment by killdayu** [comment]
> 🤣好的，我今天晚点更一版新的插件出来
> OK, I will update the plugins later.
> 
> 自动更新版其实已经做好了，最近比较忙没放出来，可以关注[推特](https://twitter.com/Elliot58616851)
> The auto update plugins verion has been finish, but I got a little busy these day, you can follow my [twitter](https://twitter.com/Elliot58616851) for latest news
> 

好的，我去看看，感谢

**Comment by elliot-bia** [comment]
自动更新插件版已放出
