### ISSUE TITLE
密码我猜不出来怎么办?

### ISSUE THREAD

**Issue by chelseasura** [elliot-bia/nessus#20]
**Describe the bug**
**描述问题**
请用精炼的语言描述问题所在

**To Reproduce**
**问题复现步骤**

用以下步骤复现：
1，第一步。。。
2，第二步。。。
3，第三步。。。

**Expected behavior**
**期待行为**
简要语言描述你期待这个程序想要响应的行为

**Screenshots**
**截图**
务必带上截图

**Desktop (please complete the following information):**
**测试环境**

**Additional context**
**其他补充**

**Comment by elliot-bia** [comment]
不做解答，关闭issue
