### ISSUE TITLE
nessus扫描时出现Network interface transient error The network interface

### ISSUE THREAD

**Issue by chenjiewei123** [elliot-bia/nessus#21]
nessus扫描时出现如下情况：
Network interface transient error
The network interface ‘\Device\NPF_{DF6D9295-830F-4A92-B0E4-D0C0C9188C87}’ was not always available for packet forgery, which may lead to incomplete results. This is likely to be a transient error due to a lack of resources on this host. To correct this error, reduce the number of scans and/or hosts scanned in parallel

师傅有碰到过这种情况吗，我的是m1pro的mac

**Comment by elliot-bia** [comment]
ARM芯片的错误应该直接找docker官方，与此项目无关
此项目推荐运行在X86_64环境

**Comment by chenjiewei123** [comment]
好的，谢谢师傅
