### ISSUE TITLE
扫描任务配置定时运行问题

### ISSUE THREAD

**Issue by m3cooper** [elliot-bia/nessus#23]
**Describe the bug**
**描述问题**
扫描任务配置定时运行的时候没响应，而且时区是无法配置的。
1) 社区配置是被砍掉了吗？ 感觉像是未配置时区造成无法保存。
2) 请问这个扫描任务是不能支持定时的吗？还是我造成不对？

![企业微信截图_16771448372233](https://user-images.githubusercontent.com/11971157/220869538-774e2487-0325-4af2-8ae9-817f3d6731b0.png)

**Comment by elliot-bia** [comment]
TZ(TimeZone）没有设置，你可以自己进bash加一下，下个版本我加进去吧

**Comment by linsihao7788** [comment]
上面的师傅设置好了吗，我找不到相关的设置TimeZone的信息

**Comment by linsihao7788** [comment]
我这边选择日期也是直接闪退回扫描页面，无法选择日期，也是因为时区导致的吗？我在docker内已经设置了TZ时区为上海并且和宿主机是一样的了

**Comment by kingsxw** [comment]
配置 -v /usr/share/zoneinfo:/usr/share/zoneinfo就好了

![image](https://user-images.githubusercontent.com/15606960/222360822-dedd685b-2d53-4d20-8503-a2a74332397b.png)

![image](https://user-images.githubusercontent.com/15606960/222360892-455f8244-4686-49e3-93a6-76a1b7b7b4a4.png)

**Comment by linsihao7788** [comment]
好的，按照大佬的思路设置了，这边正常使用了，谢谢大佬

**Comment by elliot-bia** [comment]
已修复
Have been fixed
