### ISSUE TITLE
扫同一个ip 第一个test却有主机，第二个test1却没有主机

### ISSUE THREAD

**Issue by lone0x0** [elliot-bia/nessus#26]
![截屏2023-04-24 14 22 23](https://user-images.githubusercontent.com/78702504/233915561-e175b94e-5545-4fc8-9139-0efdea11a2c8.png)
![截屏2023-04-24 14 22 31](https://user-images.githubusercontent.com/78702504/233915568-53bacbad-1a63-4d90-a6bf-94a320ba5f2e.png)

![截屏2023-04-24 14 22 59](https://user-images.githubusercontent.com/78702504/233915598-1b8dac5f-a0a5-47ac-9769-b5bec6a1109b.png)
![截屏2023-04-24 14 23 10](https://user-images.githubusercontent.com/78702504/233915616-0c3b1981-faf6-4cbb-acdd-21149d3dad40.png)
![截屏2023-04-24 14 24 02](https://user-images.githubusercontent.com/78702504/233915636-f8a1122b-a0eb-421e-ada7-aefb92657ef3.png)

**Comment by lone0x0** [comment]
ping49.233.32.87是通的

**Comment by elliot-bia** [comment]
主机存活 Host Discovery的问题

**Comment by lone0x0** [comment]
> Host Discovery

但是我用的是Basic Network Scan模式 也扫不到？
