### ISSUE TITLE
New Version v10.5.1 from stackzhao

### ISSUE THREAD

**Issue by elliot-bia** [elliot-bia/nessus#27]
> > > 已经推出新版本，不知道是否会继续开拓新版本？
> > 
> > 
> > 什么版本？
> 
> 最新版本10.5.0已经推出的

@ericzhong2010 我根据大佬镜像制作了最新的10.5.1版本
```bash
sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus -p 8834:8834 stackzhao/nessus_pj:v10.5.1
# 更新插件
sudo docker exec -it nessus /bin/bash 
bash /root/upgrade.sh
# 修改默认密码
/opt/nessus/sbin/nessuscli chpasswd --user root --new-password new_password     # 请将new_password替换为新的密码
```
接下来可以使用用户`root`，密码`new_password`进行登录

_Originally posted by @zyh001 in https://github.com/elliot-bia/nessus/issues/24#issuecomment-1509591651_

**Comment by joostgrunwald** [comment]
@elliot-bia @zyh001 I got a nessus expert trial on 10.5.1. Is it a possible idea to look if the same methodology applies here?

**Comment by elliot-bia** [comment]
I don't think so, different versions have different crack logic  
You can try

**Comment by dragongt501** [comment]
@elliot-bia hi bro, can you tell me what file, method need to patch to crack nessus? Thanks you!

**Comment by elliot-bia** [comment]
No, but you can explore on your own. I think it is not so diffcult to find out the crack logic

**Comment by elliot-bia** [comment]
经过测试，10.5.2版本破解逻辑不一样，无精力测试，无升级计划

After testing，the crack logic of 10.5.2 version is different 10.2. No energy for testing, no upgrade plan in the near feature
