### ISSUE TITLE
configuring error

### ISSUE THREAD

**Issue by alchu4n** [elliot-bia/nessus#28]
**Describe the bug**
When configuring the email, I encountered the following error.

```bash
Error: It was not possible to email this scan:
Failed to receive the SMTP banner from the service listening on port 587
```
![image](https://github.com/elliot-bia/nessus/assets/97670155/93011981-2281-48dc-8398-077ce2d7762a)

**Comment by elliot-bia** [comment]
Please check with the SMTP server owner to confirm if the settings are valid (Host, Port, Authentication Method, Encryption)

You can get more details in [community](https://community.tenable.com/s/article/SMTP-Settings-Are-Invalid)

**Comment by songhanpoo** [comment]
Hi Guys,
May I know the password to first login ?

**Comment by elliot-bia** [comment]
It has been a long time, I think you had fixed the issue, now I will close the issue
