### ISSUE TITLE
停止或重启容器后不会自动启动nessus

### ISSUE THREAD

**Issue by ID404** [elliot-bia/nessus#3]
执行docker restart nessus后，web页面无法打开
排查发现nessusd没有启动
需要执行docker exec -it ramisec_nessus /bin/bash /nessus/update.sh才能正常打开web页面：

**Comment by elliot-bia** [comment]
已修复
it has been fix

**Comment by elliot-bia** [comment]
尝试重新pull新的镜像下来即可
