### ISSUE TITLE
docker stop 无法启动？

### ISSUE THREAD

**Issue by charis3306** [elliot-bia/nessus#33]
![image](https://github.com/elliot-bia/nessus/assets/84823804/e15f2a21-c89d-4a07-8a09-52152940a75a)

**Comment by exrienz** [comment]
Having the same issue, works fine if not updating the plugins tho

**Comment by elliot-bia** [comment]
请给出详细操作过程

Please give more details

**Comment by elliot-bia** [comment]
bug fixed, please repull the images and run it again.
try 
```
docker pull ramisec/nessus
docker stop ramisec_nessus && docker rm ramisec_nessus
docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus
```
