### ISSUE TITLE
Unable to restart the container

### ISSUE THREAD

**Issue by exrienz** [elliot-bia/nessus#34]
Hi, Great job on creating the docker images. FYI I run the following command:

`docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus && docker exec -it ramisec_nessus /bin/bash /nessus/update.sh`

Now the container with the ramisec_nessus name with the latest plugin update should be ready to be used anytime. However, when I stop the container or restart the host. I can no longer start/run the container back. It automatically exits/closed.

`docker stop ramisec_nessus`

`docker start ramisec_nessus`

How to prevent this from happening? I tried with the docker checkpoint, but also unable to create the snapshot. Creating a commit also not works.

Or do we need to spin new container + update plugins every time we want to use it? How is your method?

**Comment by elliot-bia** [comment]
bug comfire in #29
It will be fix later

**Comment by elliot-bia** [comment]
bug fixed, please repull the images and run it again.
try 
```
docker pull ramisec/nessus
docker stop ramisec_nessus && docker rm ramisec_nessus
docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus
```
