### ISSUE TITLE
启动成功后，添加扫描任务失败

### ISSUE THREAD

**Issue by yangshifan-git** [elliot-bia/nessus#35]
**Describe the bug**
**描述问题**
启动成功后，点击添加扫描，就会提示状态码500的错误

**To Reproduce**
**问题复现步骤**

![image](https://github.com/elliot-bia/nessus/assets/59814204/2d99da36-230e-4368-b6f2-4bdc713687a6)

用以下步骤复现：
1，第一步。。。
2，第二步。。。
3，第三步。。。

**Expected behavior**
**期待行为**

可以进行扫描任务，目前没有开启任务的可能
![image](https://github.com/elliot-bia/nessus/assets/59814204/ae5bb145-e8e9-4568-adc3-4a403ceeb09f)

**Screenshots**
**截图**
![image](https://github.com/elliot-bia/nessus/assets/59814204/282201ec-44d9-4109-abde-ef5dee2c2f4c)

![image](https://github.com/elliot-bia/nessus/assets/59814204/ec94739c-a4fc-4d50-a34b-211191d35a3d)

**Additional context**
**其他补充**

**Comment by elliot-bia** [comment]
未更新插件

**Comment by elliot-bia** [comment]
It has been a long time, I think you had fixed the issue, now I will close the issue
