### ISSUE TITLE
scheduled scans not working

### ISSUE THREAD

**Issue by joostgrunwald** [elliot-bia/nessus#37]
Whenever I try to do a scheduled scans it keeps stuck on saving....  and does not do the scheduled scan.

I tried a clean reinstall but didn't work.

**Comment by elliot-bia** [comment]
I had beed fixed it in #23 , may be is the time zone problem. Please give more detaile

**Comment by joostgrunwald** [comment]
I fixed it, had to install zone update, but the previous solution errored for me
`
root@496aa5163c6a:/nessus# apt-get update && apt-get install -y tzdata  
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Get:2 http://mirrors.aliyun.com/ubuntu bionic InRelease [242 kB]           
Get:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3358 kB]
Get:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease [83.3 kB]    
Get:6 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1668 kB]
Get:7 http://mirrors.aliyun.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1633 kB]
Get:9 http://mirrors.aliyun.com/ubuntu bionic/main amd64 Packages [1344 kB]   
Get:10 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [23.8 kB]
Get:11 http://mirrors.aliyun.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:12 http://mirrors.aliyun.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 http://mirrors.aliyun.com/ubuntu bionic-updates/restricted amd64 Packages [1709 kB]
Get:14 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 Packages [3771 kB]
Get:15 http://mirrors.aliyun.com/ubuntu bionic-updates/multiverse amd64 Packages [30.8 kB]
Get:16 http://mirrors.aliyun.com/ubuntu bionic-updates/universe amd64 Packages [2404 kB]
Get:17 http://mirrors.aliyun.com/ubuntu bionic-backports/universe amd64 Packages [20.6 kB]
Get:18 http://mirrors.aliyun.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
Fetched 28.1 MB in 17s (1620 kB/s)                                             
Reading package lists... Error!
E: flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.
`

Then I fixed it by doing:
`
mkdir -p /var/lib/dpkg/{alternatives,info,parts,triggers,updates}  
touch /var/lib/dpkg/status  
apt-get update  
apt-get install -y tzdata  
`

**Comment by elliot-bia** [comment]
Got it, it seems like an enhancement option, I will try fix it later. 
Maybe...when I get free time....
