### ISSUE TITLE
请问镜像是关了吗

### ISSUE THREAD

**Issue by ll160803** [elliot-bia/nessus#38]
我一直无法pull镜像，我很确认不是我的网络错误

**Comment by elliot-bia** [comment]
Docker 官方仓库域名 hub[.]docker[.]com/于2023年5月18日遭遇DNS污染，目前已经无法正常访问。[详情](https://twitter.com/landiantech/status/1659219533771718656)
自行搜索挂代理方法, Fuck GFW!
<img width="608" alt="image" src="https://github.com/elliot-bia/nessus/assets/40572216/5b26f28d-bb47-4977-868e-8faaf0718ef8">

**Comment by ll160803** [comment]
谢谢谢谢谢～
