### ISSUE TITLE
报告模板

### ISSUE THREAD

**Issue by leanovv** [elliot-bia/nessus#39]
**导出的时候希望可以自定义模板**
在扫描之后，选择report，里面包含了html与csv选项，HTML只有系统默认的几种类型，可以自定义选择吗。官方的教程里是可以自定义的。https://docs.tenable.com/nessus/10_3/Content/CreateReportTemplate.htm

![2023-06-29_094002](https://github.com/elliot-bia/nessus/assets/30551116/971906c5-94d1-4997-a044-0d6b21f20905)

**Comment by elliot-bia** [comment]
好问题，我没研究过，可能是版本问题
平时我都是直接导出csv然后nessus2CN脚本一键处理翻译成中文Excel，脚本是开源改的，如果需求多的话考虑开源出来
