### ISSUE TITLE
来自awvs 的肯定

### ISSUE THREAD

**Issue by Ran-Xing** [elliot-bia/nessus#4]
fahai 说他害羞，不好意思给你点赞
![07D0936A-7BCD-4A7B-A7E4-776423FBB332](https://user-images.githubusercontent.com/73819467/180599765-d79a602a-ad71-49bf-8a2e-7d1730e935a7.jpeg)
这是我微信，欢迎一起交流扫描器

**Comment by elliot-bia** [comment]
🤣谢谢，受宠若惊！

干我们这一行的，我已经养成了0信任这个坏毛病

微信就免了吧，you can reach me in twitter, I has open the direct  message
