### ISSUE TITLE
破解失效了吗？

### ISSUE THREAD

**Issue by MagicalNOS** [elliot-bia/nessus#40]
安装时间2023年7月4日
安装后发现插件全部消失了

安装插件的截图
<img width="612" alt="image" src="https://github.com/elliot-bia/nessus/assets/63483435/29bbecaf-45b5-494a-a70a-a0d724bdd57c">

修改了Nessus密码来使用
<img width="1120" alt="image" src="https://github.com/elliot-bia/nessus/assets/63483435/22f87b5b-360c-4992-8cd8-6e56d0b7f10e">

**Comment by MagicalNOS** [comment]
求助大佬，万分感谢❤️

**Comment by elliot-bia** [comment]
搞定了没？

**Comment by qxqzx3489** [comment]
我的也这样，大哥解决了吗？

**Comment by elliot-bia** [comment]
贴出详细复现步骤和日志记录
