### ISSUE TITLE
网卡问题

### ISSUE THREAD

**Issue by deletee-china** [elliot-bia/nessus#42]
扫描报出下列错误，该如何处理网卡eno
貌似是没有权限？
不支持网络接口
192.168.0.108/10114 网络接口“eth0”不支持数据包伪造。这可以防止 Nessus 确定某些目标主机是否处于活动状态并对其执行完整端口扫描。您可以通过编辑扫描设置以禁用“Ping”（取消选中“常规”->“Ping 主机”）并向 Nessus 提供远程主机的凭据以防止发生端口扫描来部分解决此问题，但最好通过不同的网络接口进行扫描。

**Comment by elliot-bia** [comment]
我觉得是你机器问题，建议多试几台机器控制变量
