### ISSUE TITLE
破解运行一段时间后，破解失败。

### ISSUE THREAD

**Issue by 98Kstar** [elliot-bia/nessus#43]
**Describe the bug**
在按流程安装docker版本之后，进行扫描，扫描半天之后重新登录提示license error
请用精炼的语言描述问题所在
在按流程安装docker版本之后，进行扫描，扫描半天之后重新登录提示license error，并且成为免费版，只扫描给出16个ip地址结果

**To Reproduce**
**问题复现步骤**
正常安装docker版本，扫描7个ip的c段

<img width="1322" alt="image" src="https://github.com/elliot-bia/nessus/assets/41816999/191440d8-078c-421f-9912-034a6d6f7dbd">
<img width="1361" alt="image" src="https://github.com/elliot-bia/nessus/assets/41816999/592487d7-dc9c-4d03-92f9-3b2f5add8719">
<img width="146" alt="image" src="https://github.com/elliot-bia/nessus/assets/41816999/9a55a066-943a-405d-a65a-e7439432a319">

以下是前面正常扫描后突然出现的日志记录：
[Wed Jul 26 14:03:08 2023][18743.1] Logfile /opt/nessus/var/nessus/logs/nessusd.messages initialized with size-based rotation
[Wed Jul 26 14:03:08 2023][18743.1] Priority set to 0
[Wed Jul 26 14:03:08 2023][18743.1] nessusd 10.2.0 (build 20075) started
[Wed Jul 26 14:03:08 2023][18743.1] System has 2 cores and 3742MB of RAM
[Wed Jul 26 14:03:08 2023][18743.1] Linux overcommit_memory policy is set to: 0
[Wed Jul 26 14:03:08 2023][18743.1] profiled 769200 vm ops / 10msec
[Wed Jul 26 14:03:08 2023][18743.1] VM thread pool size: 2-200
[Wed Jul 26 14:03:09 2023][18743.1] Setting Scanner:  engine.min=4 engine.max=16  global.max_scans=0  global.max_hosts=1500  engine.max_hosts=16  engine.optimal_hosts=2 (scan)max_hosts=100  (scan)max_checks=5
[Wed Jul 26 14:03:09 2023][18743.1] PS thread pool size: 1-100
[Wed Jul 26 14:03:14 2023][18743.1] Could not validate the license used on this scanner
[Wed Jul 26 14:03:14 2023][18743.1] Could not validate plugin feed
[Wed Jul 26 14:03:14 2023][18743.1] WebServer thread pool size: 2-200
[Wed Jul 26 14:03:14 2023][18743.1] Nessus is ready
[Wed Jul 26 14:03:14 2023][18743.0] WebServer service is running (pid=32)
[Wed Jul 26 14:03:19 2023][18743.1] Nessus is shutting down:
[Wed Jul 26 14:03:19 2023][18743.1] WebServer service shutting down: Nessus shut down
[Wed Jul 26 14:03:19 2023][18779.1] Logfile /opt/nessus/var/nessus/logs/nessusd.messages initialized with size-based rotation
[Wed Jul 26 14:03:19 2023][18779.1] Priority set to 0
[Wed Jul 26 14:03:19 2023][18779.1] nessusd 10.2.0 (build 20075) started
[Wed Jul 26 14:03:19 2023][18779.1] System has 2 cores and 3742MB of RAM
[Wed Jul 26 14:03:19 2023][18779.1] Linux overcommit_memory policy is set to: 0
[Wed Jul 26 14:03:20 2023][18779.1] profiled 755020 vm ops / 10msec
[Wed Jul 26 14:03:20 2023][18779.1] VM thread pool size: 2-200
[Wed Jul 26 14:03:20 2023][18779.1] Setting Scanner:  engine.min=4 engine.max=16  global.max_scans=0  global.max_hosts=1500  engine.max_hosts=16  engine.optimal_hosts=2 (scan)max_hosts=100  (scan)max_checks=5
[Wed Jul 26 14:03:20 2023][18779.1] PS thread pool size: 1-100
[Wed Jul 26 14:03:20 2023][18779.1] WebServer thread pool size: 2-200
[Wed Jul 26 14:03:20 2023][18779.0] WebServer service is running (pid=24)
[Wed Jul 26 14:03:20 2023][18779.1] Nessus is ready

**Comment by elliot-bia** [comment]
找时间复现一下
你试试把镜像删了，重新pull一个下来试试

**Comment by 98Kstar** [comment]
重新下过了，一样的，第一次出现的时候就重新下载删除了，我看了下，可能是因为[Wed Jul 26 14:03:09 2023][18743.1] Setting Scanner: engine.min=4 engine.max=16 global.max_scans=0 global.max_hosts=1500 engine.max_hosts=16 engine.optimal_hosts=2 (scan)max_hosts=100 (scan)max_checks=5
这个设置中，host的max是1500个，当超过1500个的时候，他重启了，重启之后lincese就破解失效了。
