### ISSUE TITLE
新建Policies提示500 - Internal Server Error

### ISSUE THREAD

**Issue by Kfanup** [elliot-bia/nessus#44]
**Describe the bug**
**描述问题**
请用精炼的语言描述问题所在

**To Reproduce**
**问题复现步骤**

用以下步骤复现：
1，第一步。。。
2，第二步。。。
3，第三步。。。

**Expected behavior**
**期待行为**
简要语言描述你期待这个程序想要响应的行为

**Screenshots**
**截图**
务必带上截图

**Desktop (please complete the following information):**
**测试环境**

**Additional context**
**其他补充**

**Comment by Kfanup** [comment]
接口错误信息 Unable to find templates

**Comment by kuron3k0** [comment]
me too

**Comment by elliot-bia** [comment]
try delete containers and image, repull the images and reinstall

**Comment by DaDong-G** [comment]
500
Error: Unable to find templates Please contact support if this issue continues.

**Comment by elliot-bia** [comment]
已修复，请查看
https://github.com/elliot-bia/nessus/issues/50#issuecomment-1859318065
