### ISSUE TITLE
download plugins error

### ISSUE THREAD

**Issue by xiv3r** [elliot-bia/nessus#49]
i have internet but i got this error

Seems the download files is missing wget unable to get the file from the link

https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=56b33ade57c60a01058b1506999a2431&p=1ee9c89d5379a119a56498f2d5dff674

Resolving plugins.nessus.org (plugins.nessus.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'plugins.nessus.org'

**Comment by mytricker0** [comment]
I have the same problem, you maked the thread as completed, so what was your solution ?

**Comment by elliot-bia** [comment]
If you CAN NOT update successful, please CHECK the network connection!
