### ISSUE TITLE
non-scan configuration changes resulting in crack-fail

### ISSUE THREAD

**Issue by f3yc0w** [elliot-bia/nessus#50]
Unsure of the cause of this. Got about 15-20 minutes out of it before I was suddenly booted from the web-server.

All scans are stopped and a warning appears at the top letting you know that your license has either expired or something else..etc

This has been experienced twice, I'm still not sure of the common-denominator at this point. Stay tuned.

**Comment by elliot-bia** [comment]
It looks like the crack has failed or the update pack has been blocked.
Did you do anything else？

**Comment by f3yc0w** [comment]
So after using it all afternoon it seems like there's just like a few
things going on one of which is there's a setting called telemetry which
needs to go off but is also part of the problem that when you turn it off
that is when something else is being triggered I believe in response to that


I mean the crack itself shouldn't fail period right I mean it not like I
have the source code but from what I can tell I mean the program stands by
itself and then the plugins are being added with maybe some of your wizard
magic right but ultimately unless tenable is able to reach backwards
through their program right through say a back door maybe or you know
whatever else a poisoned upgrade per plugins etc.. They shouldnt have a
good way to really patch the crack, after all.. The arguable definition of
a true and fully cracked program is really just making sure it works long
enough for you to air gap it and freeze it in time 😂 Plus, given the
nature of the software, a poisoned plugin or backdoor is always a
possibility.

### HOWEVER,

While im typing this, I just tripped a flag ive tripped before. It appears
that like 90% of
of the env vars in the settings tab and it's 5 or 6 subtabs are boobie
trapped. When i have time, ill use bash or py to initiate a more efficient
one by one. But Im now 100% sure that the settings tabs are part of the
issue.

**Comment by f3yc0w** [comment]
Ill go check for airgap results when im done smoking lol, If I dont have
the same issue with RFKILL on, then we will have our answer as far as who
or where the problem is coming from

**Comment by f3yc0w** [comment]
Ran over 7 hours of unsafes, and full non-spec sweeps without any issue. Multiple system restarts, two seperate docker daemon sessions, export, moved image to another machine , resulting in a single, advance, fully-executed scan of  12 hostscan after import and moved the report documents around over MeshNet from 4 different devices through out the city...

### Non-Scan-Related, Potential
So, at this point I feel confident to say that the issue is more likely coincidental decay as opposed to any kind of real action by Tenable. Only changes to the configuration, The specific way it way it actually happens when it does definitely makes me feel like my focus should be on the immediately applied reversion of "Unlimited Licenses" back to 16. Hosts are instantaneously removed until 16 or less remain, and scans are aborted. It happens before literally every single thing except perhaps the CSS execution for the warning that pops at the top during crack-fail-event so

### Persistence
There is also definitely something on the FS that is being brought over or changed when this happens, because the issue 
I can't say what the differentiation is for which settings run the risk of breaking the mirage and which ones don't. But the crack-failure that results is persistent. I'm currently having to replace the entire image each time it happens in order to reset back to square 1. That means that the problem can almost certainly be reverse engineered backwards via wireshark
in the event Tenable whistled. I'm of the general opinion this is probably just something that came as a result of dependency changes or the like. If that is the case, I'd use fr frida-trace.


I'll burp the crack-failure event when I get home and see if anyone speaks 😛 I'll keep you updated. @elliot-bia

**Comment by harshdhamaniya** [comment]
Facing the same issue, during the scanning process after 15 mins nessus is brought back to home login screen upon successful login nessus is converted to nessus essentials and IP limit to 16IPs

![image](https://github.com/elliot-bia/nessus/assets/116166209/a383ccbd-0943-4794-94e3-7dd3778ed3ba)

![image](https://github.com/elliot-bia/nessus/assets/116166209/f90ad770-e74e-4954-be01-5d6fdc88c1bb)

Please Provide a solution for the same @elliot-bia

**Comment by B1aK2** [comment]
相同的问题，配置了nessus的代理之后破解失效：
![image](https://github.com/elliot-bia/nessus/assets/30688761/532d5bd7-19b5-4b38-93c6-8a242a2be6b2)
![image](https://github.com/elliot-bia/nessus/assets/30688761/b939692b-75af-4257-aa08-0fc0d45bfb9b)
破解失效后尝试扫描www.baidu.com主机：
![image](https://github.com/elliot-bia/nessus/assets/30688761/952067f9-2856-4726-92fb-73cbb80d5db4)

**Comment by elliot-bia** [comment]
Copy that，I would try to slove this problem in this weekend.

**Comment by elliot-bia** [comment]
Sorry, I have been f**king busy, I will solve it as soon as I have free time

**Comment by danger-dream** [comment]
Is there any update?

**Comment by elliot-bia** [comment]
The activate code had been banned, I'm tring to solved this situation
It will be upgrade at next week, ( after I finish my java code project....

**Comment by elliot-bia** [comment]
Hello, everyone! 
It's 7 o'clock in China, I'm glad to announce that new version has been release.
Just pull the lastest version.
And the usage is below:
`docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus:latest`
`docker exec -it ramisec_nessus /bin/bash  -c "/nessus/update.sh UPDATE_URL_YOU_GOT"`
The **UPDATE_URL_YOU_GOT** you need to apply in nessus [website](https://tenable.com/products/nessus/nessus-essentials) to get **an activation-code**, and generate it in this [website](https://plugins.nessus.org/v2/offline.php)
For example:
<img width="544" alt="image" src="https://github.com/elliot-bia/nessus/assets/40572216/0a821a76-060c-4b51-a1a4-f95bd56e2556">
Any stings like `aaaaaa11b2222cc33d44e5f6666a777b8cc99912` would be available, but remeber must not be the same :)
And you will get the **UPDATE_URL_YOU_GOT**
<img width="548" alt="image" src="https://github.com/elliot-bia/nessus/assets/40572216/48adee7e-8423-4e17-b54f-94641c02906e">

It's funny that this process just took me three hours, but I  procrastinated for 3 weeks even more 🤣🤣
May you guys enjoy!

**Comment by harshdhamaniya** [comment]
> Hello, everyone! It's 7 o'clock in China, I'm glad to announce that new version has been release. Just pull the lastest version. And the usage is below: `docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus:latest` `docker exec -it ramisec_nessus /bin/bash -c "/nessus/update.sh UPDATE_URL_YOU_GOT"` The **UPDATE_URL_YOU_GOT** you need to apply in nessus [website](https://tenable.com/products/nessus/nessus-essentials) to get **an activation-code**, and generate it in this [website](https://plugins.nessus.org/v2/offline.php) For example: <img alt="image" width="544" src="https://private-user-images.githubusercontent.com/40572216/291111271-0a821a76-060c-4b51-a1a4-f95bd56e2556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODAxNzYsIm5iZiI6MTcwMjk3OTg3NiwicGF0aCI6Ii80MDU3MjIxNi8yOTExMTEyNzEtMGE4MjFhNzYtMDYwYy00YjUxLWExYTQtZjk1YmQ1NmUyNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5NTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODI5MTg4NzE0OTljNGMyNDJjNzE1YjA1YjNkMTc3MTI4MDQyZGU5YzlhYjk2MzI1ZWRhYTBkY2FmNTNlNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9D9axrpQyVHRzyY7AU8nDynFVNCMMhy9jSCV5WBIlI"> Any stings like `aaaaaa11b2222cc33d44e5f6666a777b8cc99912` would be available, but remeber must not be the same :) And you will get the **UPDATE_URL_YOU_GOT** <img alt="image" width="540" src="https://private-user-images.githubusercontent.com/40572216/291113402-486988b6-352e-4d8e-9910-1308c50bc053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODAxNzYsIm5iZiI6MTcwMjk3OTg3NiwicGF0aCI6Ii80MDU3MjIxNi8yOTExMTM0MDItNDg2OTg4YjYtMzUyZS00ZDhlLTk5MTAtMTMwOGM1MGJjMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5NTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYWEzMTJhZTcyZDdiMzg4MjNiYjBhNWRmM2M4NTRlNDAwNjI1NDRkNTc2MWVhYWUyNThiYWY5NDE3NWFkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o8lv5AvATgSdOq3RH4rmStobZ6lwiCuKXrD2u_xRnh0">
> 
> It's funny that this process just took me three hours, but I procrastinated for 3 weeks even more 🤣🤣 May you guys enjoy!

Hey @elliot-bia i have tried to use the latest build, this build worked till today without any problems. But again my nessus went to compiled plugin suddenly today and again the license is seems expired.

![image](https://github.com/elliot-bia/nessus/assets/116166209/034cf01b-082c-4ecb-acab-bb52504d55aa)

**Comment by elliot-bia** [comment]
Did you restart the docker images?

**Comment by harshdhamaniya** [comment]
> Did you restart the docker images?

No i didn't restarted the docker image, Also the PC was never shutdown nor docker was restarted

**Comment by elliot-bia** [comment]
Did you restart the container?

**Comment by harshdhamaniya** [comment]
> Did you restart the container?

No sir, It was running contineously from the day you pushed the new update. It happened automatically. Nessus window went to compile plugin and then redirected to Login screen, After loggin in it showed the yellow error bar at the top where the crack seems to fail.

**Comment by elliot-bia** [comment]
ok，I'll replicate it in local
Any other infomation will be helpful

**Comment by harshdhamaniya** [comment]
If you can implement it over Nessus Professional Key, you can fetch the key from a tool i have developed to generate Nessus Professional key without form submission. which can help in direct update rather than client have to submit form get key and submit a string with key to get the URL.

**Comment by harshdhamaniya** [comment]
Any sort of temporary support to refresh unlimited status is helpful..!!

**Comment by elliot-bia** [comment]
Well, You can try run `docker exec -it ramisec_nessus /bin/bash  -c "/nessus/update.sh UPDATE_URL_YOU_GOT"` again
It will be crack again

**Comment by elliot-bia** [comment]
> If you can implement it over Nessus Professional Key, you can fetch the key from a tool i have developed to generate Nessus Professional key without form submission. which can help in direct update rather than client have to submit form get key and submit a string with key to get the URL.

No, The implement process doesn't use any activation-code, and I saw your [nessuscrack](https://github.com/harshdhamaniya/nessuscrack) tools, it's great

**Comment by harshdhamaniya** [comment]
docker exec -it ramisec_nessus /bin/bash  -c "/nessus/update.sh UPDATE_URL_YOU_GOT"

i have tried this command, it was successfull as well, but still im getting the following error with unlimited IPs scannable

![image](https://github.com/elliot-bia/nessus/assets/116166209/5dc2d717-9af6-46f0-8110-386fb41aa235)

**Comment by harshdhamaniya** [comment]
Also, The scans which are already completed when launched again, they are getting completed within a second with no results.

**Comment by elliot-bia** [comment]
> Also, The scans which are already completed when launched again, they are getting completed within a second with no results.

First, do not click the link "view your license information" above the page, just ignore it
Then, try to apply another activation-code
I think that would be helpful
