### ISSUE TITLE
关于容器重启

### ISSUE THREAD

**Issue by himywei** [elliot-bia/nessus#52]
您好：

    想问下，当容器重启时，此时插件不是最新版本，会出现什么问题呢？猜测会导致插件包被清空，然后无法扫描吗，是否还需要再次执行 docker exec -it ramisec_nessus /bin/bash /nessus/update.sh 更新插件包才能正常使用工具。

感谢回答！

**Comment by himywei** [comment]
经过两天的观察，发现nessus默认的插件更新策略:24h自更新 未生效，猜测可能是 activate code 无效导致，因为 activate code 值为 N/A

**Comment by elliot-bia** [comment]
应该是activate code请求次数太多被风控了，我打算做一个自己去申请activate code的选项功能出来

**Comment by elliot-bia** [comment]
> 还有，感觉心跳包的打印是不是可以做成 打印 nessus本身的日志 ，可以方便看扫描日志 ，日志路径：/opt/nessus/var/nessus/logs/nessusd.messages @elliot-bia

已添加
