### ISSUE TITLE
Won't Work, Plugin Rules EMPTY

### ISSUE THREAD

**Issue by tarocjsu** [elliot-bia/nessus#54]
![image](https://github.com/elliot-bia/nessus/assets/112042567/bb9a0809-1a78-4c16-aade-df8e34dbe70f)

![image](https://github.com/elliot-bia/nessus/assets/112042567/f6192649-5e48-434b-b4f6-8f87fb9d8753)

![image](https://github.com/elliot-bia/nessus/assets/112042567/8d6e7300-3874-48b7-8e61-3127caa98c8e)

**Comment by elliot-bia** [comment]
Did you use UPDATE_URL_YOU_GOT argument?

**Comment by tarocjsu** [comment]
> Did you use UPDATE_URL_YOU_GOT argument?

Yes

**Comment by tarocjsu** [comment]
[Mon Dec 25 09:02:08 2023][11.1] received signal 15 (TERM)

[Mon Dec 25 09:02:43 2023][523.1] Logfile /opt/nessus/var/nessus/logs/nessusd.messages initialized with size-based rotation

[Mon Dec 25 09:02:43 2023][523.1] Priority set to 0 

[Mon Dec 25 09:02:43 2023][523.1] nessusd 10.2.0 (build 20075) started

[Mon Dec 25 09:02:43 2023][523.1] System has 8 cores and 32087MB of RAM

[Mon Dec 25 09:02:43 2023][523.1] Linux overcommit_memory policy is set to: 0

[Mon Dec 25 09:02:43 2023][523.1] profiled 811080 vm ops / 10msec 

[Mon Dec 25 09:02:43 2023][523.1] VM thread pool size: 2-200

[Mon Dec 25 09:02:43 2023][523.1] Setting Scanner:  engine.min=16 engine.max=64  global.max_scans=0  global.max_hosts=400  engine.max_hosts=16  engine.optimal_hosts=2 (scan)max_hosts=100  (scan)max_checks=5

[Mon Dec 25 09:02:43 2023][523.1] PS thread pool size: 1-100

[Mon Dec 25 09:02:43 2023][523.1] WebServer thread pool size: 2-200

[Mon Dec 25 09:02:43 2023][523.0] WebServer service is running (pid=24)

[Mon Dec 25 09:13:01 2023][523.1] Nessus is ready

[Mon Dec 25 09:13:06 2023][523.1] Nessus is reloading: nessuscli - Plugin update from all-2.0.tar.gz-4-1214766803-1425790440.tmp 

[Mon Dec 25 09:13:14 2023][523.1] received signal 15 (TERM)

[Mon Dec 25 09:13:14 2023][800.1] Logfile /opt/nessus/var/nessus/logs/nessusd.messages initialized with size-based rotation

[Mon Dec 25 09:13:14 2023][800.1] Priority set to 0 

[Mon Dec 25 09:13:14 2023][800.1] nessusd 10.2.0 (build 20075) started

[Mon Dec 25 09:13:14 2023][800.1] System has 8 cores and 32087MB of RAM

[Mon Dec 25 09:13:14 2023][800.1] Linux overcommit_memory policy is set to: 0

[Mon Dec 25 09:13:15 2023][800.1] profiled 807090 vm ops / 10msec 

[Mon Dec 25 09:13:15 2023][800.1] VM thread pool size: 2-200

[Mon Dec 25 09:13:15 2023][800.1] Setting Scanner:  engine.min=16 engine.max=64  global.max_scans=0  global.max_hosts=400  engine.max_hosts=16  engine.optimal_hosts=2 (scan)max_hosts=100  (scan)max_checks=5

[Mon Dec 25 09:13:15 2023][800.1] PS thread pool size: 1-100

[Mon Dec 25 09:13:15 2023][800.1] WebServer thread pool size: 2-200

[Mon Dec 25 09:13:15 2023][800.0] WebServer service is running (pid=24)

[Mon Dec 25 09:13:38 2023][800.1] Nessus is ready

**Comment by elliot-bia** [comment]
show me you URL

**Comment by tarocjsu** [comment]
> show me your URL

I am use internal IP address https://192.168.120.33:8834/

**Comment by tarocjsu** [comment]
![image](https://github.com/elliot-bia/nessus/assets/112042567/4e7a7c5e-7543-476c-a1b2-7c2c14af67a4)
or should I miss-understanding ? in Plugin Rules default will empty ?

**Comment by tarocjsu** [comment]
The plugin can be found in Policies setting ?

**Comment by elliot-bia** [comment]
。。。
show me your UPDATE_URL_YOU_GOT
It's obviously your network problem that caused the plugin download to fail

**Comment by elliot-bia** [comment]
Check the download logs when your update the plugins
It should be like this:
```
[root@wwong01 ~]# wget "[https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3"](https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3)"
--2018-03-26 16:44:08--  https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3
Resolving [plugins.nessus.org](http://plugins.nessus.org/)... 54.152.120.25
Connecting to plugins.nessus.org|54.152.120.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 196166556 (187M) [application/octet-stream]
Saving to: “nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3.1”

100%[==============================================================================>] 196,166,556  105K/s   in 29m 51s 

2018-03-26 17:14:02 (107 KB/s) - “nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3.1” saved [196166556/196166556]
```
