### ISSUE TITLE
Update.sh via URL not functional

### ISSUE THREAD

**Issue by harshdhamaniya** [elliot-bia/nessus#55]
** Update.sh via URL not funtional **

Im facing an error when trying to run the command `docker exec -it ramisec_nessus /bin/bash  -c "/nessus/update.sh UPDATE_URL_YOU_GOT"` . It is reflecting authentication failure error and not updating the plugins and implementing crack to overall Nessus instance.

**Comment by elliot-bia** [comment]
Give me you full details

**Comment by water2060** [comment]
[
![img](https://github.com/elliot-bia/nessus/assets/76037438/197f87e6-e2f5-45bf-b437-47b3f2d8094e)
](url)
一直是这样

**Comment by elliot-bia** [comment]
我觉得是你的命令行有问题，并不是这个镜像有问题

**Comment by YiLin008** [comment]
命令中的格式有点问题，应该将命令和参数分开，并不需要-c选项
docker exec -it ramisec_nessus /nessus/update.sh "https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=4acded87ea1c10d690f2e4b8ac37c0a4&p=469d08272cd0b37cad4fb9047bbe340b"

**Comment by YiLin008** [comment]
命令中的格式有点问题，应该将命令和参数分开，并不需要-c选项
docker exec -it ramisec_nessus /nessus/update.sh "UPDATE_URL_YOU_GOT"
