### ISSUE TITLE
更新不成功

### ISSUE THREAD

**Issue by water2060** [elliot-bia/nessus#57]
![img](https://github.com/elliot-bia/nessus/assets/76037438/5a278b0f-a482-43e7-88e5-ab87d3fe3b74)
上面是docker的更新，以及日志

![image](https://github.com/elliot-bia/nessus/assets/76037438/2f4c1a2d-4dd6-4bdd-a187-caf086f4d887)
查看，还是没有更新

**Comment by elliot-bia** [comment]
你这根本就没把插件下载下来

**Comment by elliot-bia** [comment]
正常提示是这样的

[root@wwong01 ~]# wget "[https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3"](https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3)"
--2018-03-26 16:44:08--  https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3
Resolving [plugins.nessus.org](http://plugins.nessus.org/)... 54.152.120.25
Connecting to plugins.nessus.org|54.152.120.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 196166556 (187M) [application/octet-stream]
Saving to: “nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3.1”

100%[==============================================================================>] 196,166,556  105K/s   in 29m 51s 

2018-03-26 17:14:02 (107 KB/s) - “nessus.php?f=all-2.0.tar.gz&u=f3034e61f0983697059bcd357f73632e&p=d95704fbad2cd10480f7a638c0e3b8a3.1” saved [196166556/196166556]

**Comment by YiLin008** [comment]
命令中的格式有点问题，应该将命令和参数分开，不需要-c选项
docker exec -it ramisec_nessus /nessus/update.sh "UPDATE_URL_YOU_GOT"

**Comment by elliot-bia** [comment]
😯，没留意还能这么用，但是`bash -c`应该也可以吧

**Comment by elliot-bia** [comment]
啊，确实是可以这样

**Comment by elliot-bia** [comment]
已修改
