### ISSUE TITLE
更新提示 文件下载出错，请检查网络

### ISSUE THREAD

**Issue by liudun111** [elliot-bia/nessus#59]
使用更新命令，提示错误。 开启了VPN代理还是不行。求大神。
![PixPin_2024-02-01_11-08-55](https://github.com/elliot-bia/nessus/assets/44402090/872bd336-dab1-47be-a0de-4eb715b1a752)

**Comment by elliot-bia** [comment]
你这代理没有挂成功，自己去谷歌一下怎么给docker挂代理或者全局

**Comment by elliot-bia** [comment]
你这url都不对，自己看使用手册
