### ISSUE TITLE
一个疑问，container 如何配置目标设施，能扫描到宿主机Host OS？

### ISSUE THREAD

**Issue by makarov20211221** [elliot-bia/nessus#6]
如题

**Comment by makarov20211221** [comment]
我设置了-- privileged 和--network=host, 目测不能扫描到宿主机。

**Comment by makarov20211221** [comment]
目前我配置目标设施为  宿主机的docker0 ip (passwd方式访问宿主机，sudoer 用户，手动测试无问题)。但跑测后，Unix/ Linux Running Process Info 看起来，还是在容器内。请教下大佬：
------------
Output

    USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    root         1  0.0  0.0  18384  3112 pts/0    Ss+  Aug09   0:00 /bin/bash /nessus/run.sh start
    root        12  0.0  0.0   4552   872 pts/0    S+   Aug09   0:00 wc
    root       283  0.0  0.0   4540   120 ?        S    Aug09   0:00 /opt/nessus/sbin/nessus-service -D -q
    root       284  1.4  0.2 1018580 223052 ?      Sl   Aug09  16:12 nessusd -q
    root      4159  0.0  0.0   4636   896 ?        S    02:34   0:00 sh -c /bin/ps auxww 2>/dev/null
    root      4160  0.0  0.0  34412  2788 ?        R    02:34   0:00 /bin/ps auxww

**Comment by elliot-bia** [comment]
感觉是你扫描的目标的问题，扫描的主机IP是多少
