### ISSUE TITLE
执行 update.sh 报 401 Unauthorized

### ISSUE THREAD

**Issue by siweitang** [elliot-bia/nessus#60]
**更新插件时报401错误**

请指教~！

从 docker run -itd --name=ramisec_nessus -p 8834:8834 ramisec/nessus 开始，到申请license ，register  都成功了

进入点 new scan 后 报 500错误。

文档一路看下来 到 v3 部分，执行了根据文档操作 update 报401错误。

![微信截图_20240201212909](https://github.com/elliot-bia/nessus/assets/3838271/f7a23911-53a8-4361-ad88-4b5e23eb6d8f)

![微信截图_20240201212418](https://github.com/elliot-bia/nessus/assets/3838271/d1c507dd-eaab-4856-8648-670d18459bc3)

**Comment by siweitang** [comment]
已解决
执行 /opt/nessus/sbin/nessuscli update --all  更新完后重启服务 ，经过漫长的等待进入了系统。

**Comment by elliot-bia** [comment]
并不需要看到v3部分，另外你的重启后要检查插件是否存在
