### ISSUE TITLE
插件未成功更新

### ISSUE THREAD

**Issue by China-natian** [elliot-bia/nessus#62]
<img width="1144" alt="image" src="https://github.com/elliot-bia/nessus/assets/55696479/29abd841-1442-49e6-ae64-b75a7476167d">
<img width="1136" alt="image" src="https://github.com/elliot-bia/nessus/assets/55696479/d115d015-9963-4a33-a982-820646d18308">
按照教程走的 更新好了 ,但是没有登录nessus发现没有插件
<img width="1680" alt="image" src="https://github.com/elliot-bia/nessus/assets/55696479/107741c7-0d7e-44fd-95d4-cc951e8088dd">
<img width="1680" alt="image" src="https://github.com/elliot-bia/nessus/assets/55696479/1cd4a936-297a-4d7d-a088-b32899470a0d">

**Comment by xiaoshengyyds** [comment]
> <img alt="image" width="1144" src="https://private-user-images.githubusercontent.com/55696479/307239216-29abd841-1442-49e6-ae64-b75a7476167d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjQzNDQsIm5iZiI6MTcyODg2NDA0NCwicGF0aCI6Ii81NTY5NjQ3OS8zMDcyMzkyMTYtMjlhYmQ4NDEtMTQ0Mi00OWU2LWFlNjQtYjc1YTc0NzYxNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDRkZGYyOGZjMGQ1NDc4YWFkOGVhMzA2YmY0NmY1MTI1MDRlNWJlODEyNTRjMjdjNjdmNTk3ODM4MDMxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kkK3aEbLcQ2H3lMDZ5mZ0RmB74ksN1GsH7iFNxqCZeI"> <img alt="image" width="1136" src="https://private-user-images.githubusercontent.com/55696479/307239270-d115d015-9963-4a33-a982-820646d18308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjQzNDQsIm5iZiI6MTcyODg2NDA0NCwicGF0aCI6Ii81NTY5NjQ3OS8zMDcyMzkyNzAtZDExNWQwMTUtOTk2My00YTMzLWE5ODItODIwNjQ2ZDE4MzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYmI5NTQ4NjI1NGZjNGIzZGU1Mjk2ZWVmZTJmYjczZDM5OTZiZjI3ZTZmZTA2MzhhYTFmM2JhY2VkMmJiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0xlf_Y0oDQ44vXyHGWetuDcW-Z3Y_qDG7i03h_03sdE"> 按照教程走的 更新好了 ,但是没有登录nessus发现没有插件 <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/55696479/307239518-107741c7-0d7e-44fd-95d4-cc951e8088dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjQzNDQsIm5iZiI6MTcyODg2NDA0NCwicGF0aCI6Ii81NTY5NjQ3OS8zMDcyMzk1MTgtMTA3NzQxYzctMGQ3ZS00NGZkLTk1ZDQtY2M5NTFlODA4OGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NjYwNTJhOWE2NzhhMzQ1MWY0OGZmNzkyMTE0MzBmOGNmNGFiMDU2Mjk4MjMxY2RiMTkyNjA1MmJlZDYzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RQf4c6pYmDGIkmUksQ8WnI6NpLbv589DFa8ngjOPKpo"> <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/55696479/307239671-1cd4a936-297a-4d7d-a088-b32899470a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjQzNDQsIm5iZiI6MTcyODg2NDA0NCwicGF0aCI6Ii81NTY5NjQ3OS8zMDcyMzk2NzEtMWNkNGE5MzYtMjk3YS00ZDdkLWEwODgtYjMyODk5NDcwYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxODU1MWZkYjRkMzcwZGEwNzc2Y2FjM2JlYmZkYmRhYTMyYTc1ZDU1MDI4MWY4YjQ1NTgwOTU3MWM0YjdlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dtVNWtqUJhYh6kNBXwqy1Y9P8JHfbqNLriypjOR2_Y">

朋友，你和我一样，激活码那里显示：N/A，不知道这个会不会有影响；另外我在插件规则里也没有发现，现在解决了吗
