### ISSUE TITLE
/opt/nessus/sbin/nessuscli update --all 提示 无效的

### ISSUE THREAD

**Issue by saviourp** [elliot-bia/nessus#65]
<img width="1102" alt="微信图片_20240409105957" src="https://github.com/elliot-bia/nessus/assets/91475772/05649a7e-7391-497f-8747-2024c2ea87fa">

**Comment by elliot-bia** [comment]
Network error

Otherwise, using command `docker exec -it ramisec_nessus /nessus/update.sh "UPDATE_URL_YOU_GOT"`

**Comment by saviourp** [comment]
UPDATE_URL_YOU_GOT 这个填啥？填红框框里面的东西吗？
![Uploading 微信图片_20240409111752.png…]()

**Comment by saviourp** [comment]
UPDATE_URL_YOU_GOT 这个填啥？填红框框里面的东西吗？
<img width="1280" alt="微信图片_20240409111752" src="https://github.com/elliot-bia/nessus/assets/91475772/b419d920-3a1c-4659-9769-6f1ab86c06e5">
