### ISSUE TITLE
更新扫描后许可证过期

### ISSUE THREAD

**Issue by dkive** [elliot-bia/nessus#7]
更新扫描后许可证过期

**Comment by elliot-bia** [comment]
> 更新扫描后许可证过期

我这边经过测试，没问题，请自行重新pull一份最新latest版本

**Comment by elliot-bia** [comment]
> what is the password?

check the README, and you will find the answer

**Comment by dkive** [comment]
> 密码是什么？

U2FsdGVkX19WZv+QOe8awVyJwXDPSNSIC1X4AMNA4+3rO8mL/3HZ+mS/Or3DhcWXKs0WHfvOH1q/YNtVdXnaHg==
tips: github/elliot-bia
